name: nomads
favicon: null
layout_spectrum: 0.62709
typography_spectrum: 0.4723530956543982
style: the-composer
title: Nomads
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-48515502-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF5335'
    - '#B39C85'
    - '#306E73'
    - '#3B424D'
    - '#1D181F'
  brandStrength: 0.6744622972328216
  lightness: 0.5308045032434165
  saturation: 0.369577081175521
  rhythmicContrast: 0.45475224521942437
purpose: []
