name: nomads
favicon: null
layout_spectrum: 0.74289
typography_spectrum: 0.50134
title: Nomads
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-48515502-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e0e0'
    - '#d80000'
    - '#bd4144'
    - '#414141'
    - '#848485'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
